# Configuration for Faker to generate investment advisor-client conversations
---
name: "investment-advisor-client-dataset"
version: "1.0.0"
description: "A synthetic dataset of conversations between investment advisors and clients"
tags:
  - investment_advisory
  - finance
  - synthetic_data
  - conversation
  - entity_tagging

# LLM provider configuration
llm:
  provider: "gemini"
  model: "gemini-1.5-flash-002"
  project_id: "${PROJECT_ID}"         # Will be replaced with env var
  location: "${LOCATION}"             # Will be replaced with env var
  credentials_path: "${GOOGLE_APPLICATION_CREDENTIALS}"  # Service account credentials

  # Generation parameters (can be overridden in conversation section)
  temperature: 0.7
  top_p: 0.95
  top_k: 40
  max_tokens: 1024

# Dataset generation parameters
dataset:
  num_conversations: 10  # Increased number of conversations
  formats: ["split", "json", "jsonl"]  # List of output formats to generate
  #output_dir: "${OUTPUT_DIR}"          # Will be replaced with env var
  output_dir: "/tmp/faker_output"

# Conversation parameters
conversation:
  roles:
    - client
    - advisor
  min_messages: 2  # Shorter conversations
  max_messages: 15 # More long conversations
  domains:
    - market_news
    - trade_discussion
    - deal_discussion
    - market_analysis
    - portfolio_review
    
  # Predefined speakers with custom IDs
  speakers:
    advisors:
      - id: "advisor_1"
        name: "John Smith"
        role: "advisor"
        metadata: 
          experience: "senior"
          specialty: "retirement planning"
      - id: "advisor_2"
        name: "Sarah Johnson"
        role: "advisor"
        metadata:
          experience: "mid-level"
          specialty: "growth stocks"
    clients:
      - id: "client_1"
        name: "Michael Brown"
        role: "client"
        metadata:
          risk_tolerance: "moderate"
          investment_goal: "retirement"
      - id: "client_2"
        name: "Emily Wilson"
        role: "client"
        metadata:
          risk_tolerance: "aggressive"
          investment_goal: "growth"
  
  # Generation approach parameters
  use_hybrid_approach: true       # Enable hybrid approach for better quality
  parallel_enhancement: true      # Enable parallel metadata enhancement
  max_parallel_enhancement: 10    # Increased for more performance
  use_batch_requests: true        # Use batch requests for message enhancement
  batch_chunk_size: 20            # Increased for more performance
  enforce_two_person: true        # Strictly limit to two-person conversations
  
  # Dynamic fields example - these can be referenced in templates with {{field_name}}
  dynamic_fields:
    advisor_title:
      - "Senior Financial Advisor"
      - "Wealth Management Specialist"
      - "Investment Strategist"
      - "Portfolio Manager"
    client_age:
      - "35"
      - "42"
      - "56"
      - "67"
      - "28"
    meeting_type:
      - "Initial Consultation"
      - "Portfolio Review"
      - "Retirement Planning"
      - "Tax Strategy"

  # Rate limiting and performance parameters
  calls_per_minute: 120           # Increased API calls per minute (rate limit)
  max_parallel_calls: 20          # Increased parallel API calls allowed

  # Caching parameters
  use_cache: true                 # Enable response caching
  cache_size: 2000                # Increased cache size
  
  # Generation parameters specific to conversations (overrides llm section)
  temperature: 0.9                # Higher temperature for more diverse outputs
  
  # Additional variables to use in templates
  variables:
    advisor_firm: "Stonks & Co."
    tickers:
      - "AAPL"
      - "MSFT"
      - "GOOG"
      - "AMZN"
      - "TSLA"
      - "NVDA"
      - "JPM"
      - "BAC"
      - "WFC"
      - "PYPL"
      - "SQ"
      - "COIN"
      - "GME"
      - "AMC"
      - "SPY"
    market_sectors:
      - "Technology"
      - "Finance"
      - "Healthcare"
      - "Consumer Goods"
      - "Energy"
      - "Real Estate"
      - "Industrial"
    investment_styles:
      - "growth"
      - "value"
      - "income"
      - "dividend"
      - "index"
    client_experience_levels:
        - "novice"
        - "intermediate"
        - "experienced"

# Prompt templates
templates:
  # System prompt to control generation (optional)
  system_prompt: |
    You are an expert in generating realistic conversational data between investment advisors and clients.
    Your task is to create authentic-sounding conversations that include all the requested metadata.
    The conversations should include diverse topics such as market news, trade discussions, and formal market analysis.
    The content should be diverse, but always professional and inoffensive.
    The conversations should also range in formality, and length (short and informal vs long and formal).
    The entities and topics should also be relevant to the financial industry.
    
    CRITICAL INSTRUCTION: You MUST use the actual names provided in your output conversation.
    - For advisor, use ONLY the specific name provided (e.g., "John Smith", "Sarah Johnson")
    - For client, use ONLY the specific name provided (e.g., "Michael Brown", "Emily Wilson")
    - You MUST directly reference these names in the conversation content
    - Personalize the conversation by having the advisor address the client by their name
    - Personalize client messages to occasionally mention the advisor by name
    - Your generated messages MUST include several instances of these real names
    - NEVER output template syntax like {{advisor_name}} or {{client_name}} - use the actual name values instead
    - ONLY use the exact roles you're given (like "advisor" and "client") - NEVER introduce other roles like "trader" or "researcher" that weren't specified
    
    EXAMPLES:
    
    ✅ CORRECT: "Hello Michael Brown, I'm John Smith. Let me review your portfolio allocation."
    ❌ INCORRECT: "Hello {{client_name}}, I'm {{advisor_name}}. Let me review your portfolio allocation."
    
    ✅ CORRECT: "John Smith called earlier about the recent market volatility. When can we schedule a follow-up?"
    ❌ INCORRECT: "{{advisor_name}} called earlier about the recent market volatility. When can we schedule a follow-up?"
    
  # Conversation script template to guide the flow of conversation 
  conversation_script: |
    Create a conversation script/outline between {{roles_0}} ({{speaker1_name}}) and {{roles_1}} ({{speaker2_name}}).
    
    The outline should determine the flow of who speaks when, including when the same person might speak twice in a row.
    
    Domain: {{domain}}
    Meeting Type: {{meeting_type}}
    
    The conversation should have between {{min_messages}} and {{max_messages}} message turns.
    
    Output the script as a JSON array with this format:
    [
      {
        "speaker": "{{roles_0}}",
        "speaker_name": "{{speaker1_name}}",
        "subject": "Brief description of what they'll talk about",
        "consecutive": false
      },
      {
        "speaker": "{{roles_1}}",
        "speaker_name": "{{speaker2_name}}",
        "subject": "Brief description of what they'll talk about",
        "consecutive": false
      },
      {
        "speaker": "{{roles_0}}",
        "speaker_name": "{{speaker1_name}}",
        "subject": "Follow-up point - this is a consecutive message",
        "consecutive": true
      }
    ]
    
    IMPORTANT:
    1. Make sure the conversation has a logical flow
    2. Only use "consecutive": true when it makes sense for someone to speak twice in a row
    3. This script will guide the actual message generation
    4. Natural conversations sometimes have consecutive messages from the same speaker, but not too many
    5. For a conversation with {{min_messages}}-{{max_messages}} messages, include 1-3 consecutive messages where appropriate

  # Main conversation generation template
  conversation: |
    Generate a realistic conversation between an investment advisor and a client for {{advisor_firm}}.
    
    IMPORTANT: This conversation should ONLY include messages from the following roles:
    {{roles}}
    Do NOT introduce any other roles like "trader" or "researcher" that aren't specified above.

    Advisor: {{advisor_name}} ({{advisor_id}})
    Advisor Title: {{advisor_title}}  
    Client: {{client_name}} ({{client_id}})
    Client Age: {{client_age}}
    Meeting Type: {{meeting_type}}
    Domain: {{domain}}
    Investment Style: {{random(investment_styles)}}
    Client Experience Level: {{random(client_experience_levels)}}
    
    The conversation should have between {{min_messages}} and {{max_messages}} total messages.
    The conversation may be short and informal or long and formal.
    
    For each message, include the following metadata:
    - sentiment (positive, neutral, negative)
    - intent (e.g., greeting, question, clarification, recommendation, update, agreement, closing)
    - entities (list of important named entities mentioned, like tickers, company names, market sectors)
    - topics (list of topics discussed in the message, such as general market news, specific stock news, deals, and formal analysis)
    - formality (formal, casual, technical)
    
    Format the output as a JSON array with the following structure:
    [
      {
        "role": "client",
        "content": "...",
        "sentiment": "...",
        "intent": "...",
        "entities": ["...", "..."],
        "topics": ["...", "..."],
        "formality": "..."
      },
      {
        "role": "advisor",
        "content": "...",
        "sentiment": "...",
        "intent": "...",
        "entities": ["...", "..."],
        "topics": ["...", "..."],
        "formality": "..."
      },
      ...
    ]
    
    NAME USAGE REQUIREMENTS:
    1. You MUST use the actual advisor name "{{advisor_name}}" multiple times in the advisor's messages
    2. You MUST use the actual client name "{{client_name}}" multiple times in the conversation
    3. The advisor MUST address the client by name at least twice
    4. The client should occasionally mention the advisor by name
    5. NEVER use template syntax ({{name}}) in the output content - use the actual name values

    EXAMPLES OF CORRECT NAME USAGE (assuming advisor_name is "John Smith" and client_name is "Michael Brown"):
    ✅ "Hello Michael Brown, this is John Smith from {{advisor_firm}}. How are you today?"
    ✅ "John Smith mentioned that we should consider increasing our exposure to technology stocks."
    ✅ "I've reviewed your portfolio, Michael Brown, and I have some recommendations."
    ✅ "Thank you for your insights, John Smith. I'll consider your recommendation."

    Remember: In your output, replace any {{name}} placeholders with the actual names provided:
    - Advisor: "{{advisor_name}}"
    - Client: "{{client_name}}"
    
    CHECK your final output carefully to ensure all placeholders are replaced with real names!

  # Additional templates for generating personas (optional)
  client_persona: |
    Create a detailed persona for a client receiving investment advice at {{advisor_firm}}.

    Include:
    - Age and demographic information
    - Risk tolerance (low, medium, high)
    - Investment goals (retirement, growth, income)
    - Client experience level: {{random(client_experience_levels)}}
    - Preferred communication style (formal, casual, technical)
    - Background and profession (if relevant)

    Format as a JSON object with appropriate fields.

  advisor_persona: |
    Create a detailed persona for an investment advisor at {{advisor_firm}}.

    Include:
    - Experience level (junior, mid-level, senior)
    - Specialization areas (e.g., growth, dividends, sector-specific)
    - Communication style (formal, technical, empathetic, etc.)
    - Certifications (if relevant)
    - Investment philosophy

    Format as a JSON object with appropriate fields.
